name: first-workflow

on:
  push:
    branches: master

jobs: 
  run-first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display hello text
        run: echo "Hello-world!"
      - name: Display goodbye text
        run: echo "Goodbye world!"