name: first-workflow

on:
  push:
    branches: main

jobs:
  run-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display hello text
        run: echo "Hello-world!"
      - name: Display goodbye text
        run: echo "Goodbye world!"
      - name: Check node version
        run: |
          node -v
          npm -v
