name: eleventh-workflow
on: push

jobs:
  work-with-secrets:
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: show variables
        run: |
          echo "${{ vars.PROFESSION }}"
          echo "${{ secrets.SECRET_NAME }}"
