name: twelfth-workflow
on: push

# Status check functions: failure() success() always() canceled()

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Failure Step
        id: error-step
        run: exit 1
      - name: Runs after failure
        if: ${{ failure() && steps.error-step.conclusion == 'failure' }}
        run: echo "I'm running becouse first step was failed"

  job2:
    runs-on: ubuntu-latest
    needs: job
    if: ${{ failure() }}
    steps:
      - name: Allert
        run: echo "The Previous job was failed"
