name: fourteenth-workflow
on: [push]

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Math expression
        run: expr 2 + 2 > math-result.txt

      - name: Creating artifact
        uses: actions/upload-artifact@v4 #екшн для створення артефакту
        with:
          name: math-result # назва файлу по якій до нього можна звертатися і використовувати пізніше
          path: math-result.txt # шлях до файлу з якого створювати артефакт
          retention-days: 5 #кількість днів зберігання артефакту

  work-with-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 # екшн для використання артефакту (на другому раннері)
        with:
          name: math-result # назва артефакту для використання
      - name: Using artifact
        run: |
          value=`cat math-result.txt`
          echo $value
