name: fourteenth-workflow
on: [push]

jobs:
  work-with-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Math expression
        run: expr 2 + 2 > math-result.txt

      - name: Creating artifact
        uses: actions/upload-artifact@v4
        with:
          name: math-result # назва файлу по якій до нього можна звертатися і використовувати пізніше
          path: math-result.txt # шлях до файлу з якого створювати артефакт
          retention-days: 5
