name: second-workflow

on:
  push:
    branches: main

jobs:
  run-first-ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display hello text
        run: echo "Hello from first Ubuntu runner!"

  run-first-windows-job:
    runs-on: windows-latest

    steps:
      - name: Display hello text
        run: echo "Hello from first Windows runner!"

  run-second-job:
    runs-on: ubuntu-latest
    needs: [run-first-ubuntu-job, run-first-windows-job]

    steps:
      - name: Second Hello
        run: echo "Hello from second runner"
