name: third-workflow
on: push

jobs:
  run-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checking files
        run: |
          pwd
          ls -a
      - name: Geting files from repo
        #uses: actions/checkout@v4
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: Checking files again
        run: |
          ls -a
