name: eight-workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the Title
        type: string
        required: true
        default: "Hello World!"

jobs:
  first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Show input text.
        run: |
          echo "Title: ${{ inputs.titleCustom }}""
