name: nineth-workflow
on: [push]
run-name: "Display commiter info from context"

jobs:
  showing-context:
    runs-on: ubuntu-latest

    steps:
      - name: Context and Expressions
        id: context-expressions
        run: echo '${{ github.event.commits.committer }}'
