name: eight-workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the Title
        type: string
        required: true
        default: "Hello World!"
      selectCustom:
        description: Select Value
        type: choice
        required: true
        options:
          - Value 1
          - Value 2
          - Value 3
        default: "Value 2"
      checkCustom:
        description: Checkbox
        type: boolean
        required: false

jobs:
  first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Show input text.
        run: |
          echo "Title: ${{ inputs.titleCustom }}"
          echo "Title: ${{ inputs.selectCustom }}"
          echo "Title: ${{ inputs.checkCustom }}"
